[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"
